New feature
chinweokwu/chinweokwu-appletunes pull request #1
Opened 2020-02-11 13:15 UTC by chinweokwu

. This project is about creating a replica apple page, and new-feature branch is the final branch and the main branch of this project

2020-02-11 13:49 UTC, rOluochKe requested changes
Hello @chinweokwu 

### You have done a good job so far, however, there are a few changes you need to make.
- In your navigation, use the background gradient to achieve the design
![Screenshot from 2020-02-11 16-46-22](https://user-images.githubusercontent.com/8114528/74241941-123aeb00-4cee-11ea-84f2-99833844a674.png)
- Write a more descriptive pull request stating what you have worked on the project.
- The spacing between your thumbnails images is big, reduce it
![Screenshot from 2020-02-11 16-44-06](https://user-images.githubusercontent.com/8114528/74241819-d4d65d80-4ced-11ea-99df-0390c5d8b7cf.png)
- Your footer is still off, refer the original website
![Screenshot from 2020-02-11 16-45-36](https://user-images.githubusercontent.com/8114528/74241900-fcc5c100-4ced-11ea-958a-3159b917de9f.png)
- Configure stickler well to help with the linting

- Make the changes and resubmit for another code review.
- Happy coding!

- For assistance: Contact me @rOluochKe

2020-02-11 14:30 UTC, chinweokwu commented
Hi Raymond,
the images and the size are good on my screen i don't know how to adjust to
fix a bigger screen

On Tue, Feb 11, 2020 at 2:49 PM Raymond Oluoch <notifications@github.com>
wrote:

> *@rOluochKe* requested changes on this pull request.
>
> Hello @chinweokwu <https://github.com/chinweokwu>
> You have done a good job so far, however, there are a few changes you need
> to make.
>
>    -
>
>    In your navigation, use the background gradient to achieve the design
>    [image: Screenshot from 2020-02-11 16-46-22]
>    <https://user-images.githubusercontent.com/8114528/74241941-123aeb00-4cee-11ea-84f2-99833844a674.png>
>    -
>
>    Write a more descriptive pull request stating what you have worked on
>    the project.
>    -
>
>    The spacing between your thumbnails images is big, reduce it
>    [image: Screenshot from 2020-02-11 16-44-06]
>    <https://user-images.githubusercontent.com/8114528/74241819-d4d65d80-4ced-11ea-99df-0390c5d8b7cf.png>
>    -
>
>    Your footer is still off, refer the original website
>    [image: Screenshot from 2020-02-11 16-45-36]
>    <https://user-images.githubusercontent.com/8114528/74241900-fcc5c100-4ced-11ea-958a-3159b917de9f.png>
>    -
>
>    Configure stickler well to help with the linting
>    -
>
>    Make the changes and resubmit for another code review.
>    -
>
>    Happy coding!
>    -
>
>    For assistance: Contact me @rOluochKe <https://github.com/rOluochKe>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/chinweokwu/chinweokwu-appletunes/pull/1?email_source=notifications&email_token=AKSZYF77SGFAYJJF5RQJEQLRCKUFNA5CNFSM4KTATJF2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCVBFITY#pullrequestreview-356668495>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKSZYF6NZGGE74ERJL5VXMDRCKUFNANCNFSM4KTATJFQ>
> .
>

2020-02-11 23:17 UTC, kobiyoyo commented
## Pull Request under review, by Adama Chubiyojo Desmond (TSE)

2020-02-11 23:42 UTC, kobiyoyo requested changes
## Hi @chinweokwu     ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, but there are a few more things required. 
### Navigation 
- [ ] Any time a link is hovered over the cursor changes but your links on the navbar don't, that should be fixed.

### Background
- [x] The background image isnt covering the whole page,lets fix that.
![1](https://user-images.githubusercontent.com/23278161/74289248-c9efed00-4d2e-11ea-89ea-786309c416f8.png)

### Footer
- [x] Please align the footer links to look like the original.
### Original  Version
![2](https://user-images.githubusercontent.com/23278161/74183124-9fc20080-4c44-11ea-8d29-d9ea03e15311.png)

### Your  Version 
![1](https://user-images.githubusercontent.com/23278161/74288922-0a9b3680-4d2e-11ea-946f-d9dd631d640e.png)
 - [x] Please lets fix this broken image link
![2](https://user-images.githubusercontent.com/23278161/74289066-64036580-4d2e-11ea-94c8-dafa6d3a9860.png)


### Make changes and submit another code review request.
*Happy coding*

2020-02-12 02:13 UTC, chinweokwu commented
hi,
i have tried to fix the nav link issues. but its no working would you mind
just checking it for me pls


On Wed, Feb 12, 2020 at 12:42 AM Chubi Adama <notifications@github.com>
wrote:

> *@kobiyoyo* requested changes on this pull request.
> Hi @chinweokwu <https://github.com/chinweokwu>
> <https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png> Great
> Job so far, but there are a few more things required. Navigation
>
>    - Any time a link is hovered over the cursor changes but your links on
>    the navbar don't, that should be fixed.
>
> Background
>
>    - The background image isnt covering the whole page,lets fix that.
>    [image: 1]
>    <https://user-images.githubusercontent.com/23278161/74289248-c9efed00-4d2e-11ea-89ea-786309c416f8.png>
>
> Footer
>
>    - Please align the footer links to look like the original.
>
> Original Version
>
> [image: 2]
> <https://user-images.githubusercontent.com/23278161/74183124-9fc20080-4c44-11ea-8d29-d9ea03e15311.png>
> Your Version
>
> [image: 1]
> <https://user-images.githubusercontent.com/23278161/74288922-0a9b3680-4d2e-11ea-946f-d9dd631d640e.png>
>
>    - Please lets fix this broken image link
>    [image: 2]
>    <https://user-images.githubusercontent.com/23278161/74289066-64036580-4d2e-11ea-94c8-dafa6d3a9860.png>
>
> Make changes and submit another code review request.
>
> *Happy coding*
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/chinweokwu/chinweokwu-appletunes/pull/1?email_source=notifications&email_token=AKSZYF6WXLPWDSXG4AEC3ODRCMZVNA5CNFSM4KTATJF2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCVEK3XY#pullrequestreview-357084639>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKSZYFY6AJMNOY4EG6S77EDRCMZVNANCNFSM4KTATJFQ>
> .
>

2020-02-12 04:08 UTC, euqueme requested changes
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hi @chinweokwu :wave: 

### This is a good effort, :muscle:  I can see you have done some changes required by the previous TSE's, but you have to complete all the changes to get the approval

## Hover Issue

- [x] I have commented on your code with something that worked for me in my computer basically, you don't need the div with the .bg-image class, because it's preventing you from accessing your navbar, that's why you don't see the hover styling (of course you'd have to restyle a little so let's do it! :raised_hands: ).

 ## Building with gradients

- [x] please remove the url image in your gradient as this has to be achieved using only colors

## Footer

- [x] please align the footer links to make it look like the original as it was requested by the previous reviewer

## Generals

- [x] Validate your HTML file using this [validator](https://validator.w3.org/#validate_by_upload)

- [ ] Linters: you have linter errors do not submit back unless you have a green check in the last commit :heavy_check_mark: 

### Thats it! :raised_hands: 

### Please :pray:  do the changes :memo: and submit back for a code review when you are done :rocket: 

Happy Coding! :woman_technologist: 

Any questions? reach to me on slack **@ Maru**

PROJECT STATUS: REQUESTED CHANGES :vertical_traffic_light:

2020-02-12 04:08 UTC, euqueme commented on styles.css
> +  background: -webkit-gradient(linear, 0 0, 0 100%, from(rgba(0, 0, 0, .2)), color-stop(0.05, rgba(0, 0, 0, 0)), color-stop(0.97, rgba(0, 0, 0, 0)), to(rgba(0, 0, 0, .45))), -webkit-gradient(linear,
- [ ] Remove the url image from the gradient in line #29 as it has to be achieved using only colors and not images

2020-02-12 04:08 UTC, euqueme commented on index.html
> +    <div class="bg-img">
do this change to make your hovers work: delete the div on line #16 (just the div not the content) and pass the styling from the .bg-img class to the #showcase id

2020-02-12 04:08 UTC, euqueme commented on README.md
> +-
Delete the hyphen  `-`  in line #13

2020-02-13 10:29 UTC, nikasulo requested changes
# Great work @chinweokwu ! :medal_military: 
Your work looks very exquisite and it came together very nicely :ok_hand: , however, there is one change I have to propose, based on the hard requirements for this project. Please consider it stronlgly! When you have made the appropriate changes, please request another review :handshake: 

#### Use of background images
Please consider that as per the requirements for this project, the images in the footer are supposed to be `<div>` tags with their `background-image` properties set to the image URL and not image tags inside divs
![screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/building_with_backgrounds_and_gradients/background_image_requirement.png)

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

2020-02-14 04:45 UTC, addod19 commented
## Pull Request under review by Daniel Larbi Addo (TSE)

2020-02-14 05:08 UTC, addod19 commented
## Pull Request under review by Daniel Larbi Addo (TSE)

2020-02-14 05:11 UTC, addod19 requested changes
## Status: Require changes 🔴

Hi @chinweokwu, you did a great job making changes requested by previous reviewers. 👍 However, we still have left out some requirements. Find comments below: 😄 
- Kindly fix the warning returned by [HTML markup](https://validator.w3.org/)
![ap3](https://user-images.githubusercontent.com/46388113/74502983-5ba25a80-4ee7-11ea-8c9a-e2bab5e65232.PNG)
 - Currently, the bottom elements are not links but they should be wrapped with ```<a>```
![ap4](https://user-images.githubusercontent.com/46388113/74503100-c5226900-4ee7-11ea-9a17-d7f8bd76acab.PNG)

Kindly make these changes and submit another code review 🙂 
Happy coding 💻 
Daniel Larbi Adoo

2020-02-14 10:01 UTC, chinweokwu commented
hi larbi,
can you pls explain what i should do here because i don't understand this
[image: ap4]
<https://user-images.githubusercontent.com/46388113/74503100-c5226900-4ee7-11ea-9a17-d7f8bd76acab.PNG>

On Fri, Feb 14, 2020 at 6:11 AM Daniel Larbi Addo <notifications@github.com>
wrote:

> *@addod19* requested changes on this pull request.
> Status: Require changes 🔴
>
> Hi @chinweokwu <https://github.com/chinweokwu>, you did a great job
> making changes requested by previous reviewers. 👍 However, we still have
> left out some requirements. Find comments below: 😄
>
>    - Kindly fix the warning returned by HTML markup
>    <https://validator.w3.org/>
>    [image: ap3]
>    <https://user-images.githubusercontent.com/46388113/74502983-5ba25a80-4ee7-11ea-8c9a-e2bab5e65232.PNG>
>    - Currently, the bottom elements are not links but they should be
>    wrapped with <a>
>    [image: ap4]
>    <https://user-images.githubusercontent.com/46388113/74503100-c5226900-4ee7-11ea-9a17-d7f8bd76acab.PNG>
>
> Kindly make these changes and submit another code review 🙂
> Happy coding 💻
> Daniel Larbi Adoo
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/chinweokwu/chinweokwu-appletunes/pull/1?email_source=notifications&email_token=AKSZYF3YHVOX5SHSYGSQMZLRCYRZNA5CNFSM4KTATJF2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCVQZBMI#pullrequestreview-358715569>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKSZYF2NICCCN42WYQBRTRTRCYRZNANCNFSM4KTATJFQ>
> .
>

2020-02-14 17:38 UTC, addod19 approved these changes
## Status: Approved ✈️ 

Hi @chinweokwu, congratulations on a great job done. 👌 You can go ahead and merge to master and submit project completion form. 😄  Good luck with your next project.

Happy coding 💻 
Daniel Larbi Addo

2020-02-14 19:48 UTC, merged